### ISSUE TITLE
MOBILE: Glitchy subheadings - most of them flicker in and out and disappear

### ISSUE THREAD

**Issue by openhousepictures** [philhancox/openhousepictures#6] opened 2023-09-13 11:18 UTC
https://github.com/philhancox/openhousepictures/assets/144906896/a4353597-9d3c-466f-b1c3-d2f02cefbdf2

**Comment by philhancox** [comment] 2023-09-17 11:47
Duplicate of #1

**Closed by philhancox** 2023-09-17 11:47 UTC
